[project]
name = "readme-utils"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "mistune>=3.0.2",
    "pytest>=8.3.4",
    "typer>=0.15.1",
]

[tool.uv]
dev-dependencies = [
    "nuitka>=2.5.7",
]
